clc;
clear all;
% w=0.9;
% cover_image=imread('test.jpg');
% watermark=imread('watermark1.jpg');
% 
% F=fft2(im2double(cover_image));
% [a, b, c]=size(F);
% watermark_R=double(watermark(:, :, 1));
% watermark_G=double(watermark(:, :, 2));
% watermark_B=double(watermark(:, :, 3));
% watermark_R=imresize(watermark_R, [a/2,b/2]);
% watermark_G=imresize(watermark_G, [a/2,b/2]);
% watermark_B=imresize(watermark_B, [a/2,b/2]);
% F(1:a/2, 1:b/2, 1)=F(1:a/2, 1:b/2, 1)*w+watermark_R*(1-w);
% F(1:a/2, 1:b/2, 2)=F(1:a/2, 1:b/2, 2)*w+watermark_G*(1-w);
% F(1:a/2, 1:b/2, 3)=F(1:a/2, 1:b/2, 3)*w+watermark_B*(1-w);
% figure(1);
% imshow(real(F),[0,255]);
% imwrite(real(F),'embeding.png');
% output=real(ifft2(F));
% figure(2);
% imshow(output);
% imwrite(output,'watermarked.png');
origin=imread('watermarked.png');
%output=imrotate(output,30,'crop');
%output=imnoise(output, 'salt & pepper', 0.01);
[a,b,c]=size(origin);
origin_R=imresize(origin(:,:,1),[a/2,b/2]);
origin_G=imresize(origin(:,:,2),[a/2,b/2]);
origin_B=imresize(origin(:,:,3),[a/2,b/2]);
output=cat(3,origin_R,origin_G,origin_B);
imwrite(output,'tort.png');
extracted=fft2(output);
figure(3);
imshow(real(extracted),[0,255]);
imwrite(real(extracted),'extracted.png');